import {
  defineConfig,
  presetUno,
  presetAttributify,
  presetIcons,
  transformerDirectives,
} from 'unocss'

export default defineConfig({
  presets: [
    presetUno(),
    presetAttributify(),
    presetIcons({
      scale: 1.2,
      warn: true,
      extraProperties: {
        'display': 'inline-block',
      },
    }),
  ],
  transformers: [transformerDirectives()],
  shortcuts: {
    'flex-center': 'flex items-center justify-center',
    'flex-between': 'flex items-center justify-between',
  },
  safelist: [
    // Sidebar nav icons
    'i-lucide-layout-dashboard',
    'i-lucide-book-text',
    'i-lucide-list-tree',
    'i-lucide-users',
    'i-lucide-globe',
    'i-lucide-pen-line',
    'i-lucide-spline',
    'i-lucide-shield-check',
    'i-lucide-sparkles',
    'i-lucide-book-open',
    'i-lucide-inbox',
    // Sidebar collapse
    'i-lucide-panel-left-open',
    'i-lucide-panel-left-close',
    // Header & nav
    'i-lucide-arrow-left',
    'i-lucide-feather',
    // Common action icons
    'i-lucide-plus',
    'i-lucide-pencil',
    'i-lucide-trash-2',
    'i-lucide-save',
    'i-lucide-check',
    'i-lucide-x',
    'i-lucide-zap',
    'i-lucide-undo-2',
    'i-lucide-rotate-ccw',
    'i-lucide-refresh-cw',
    'i-lucide-send',
    'i-lucide-download',
    'i-lucide-arrow-right',
    'i-lucide-chevron-up',
    'i-lucide-chevron-down',
    'i-lucide-loader-circle',
    'i-lucide-triangle-alert',
    'i-lucide-quote',
    'i-lucide-bookmark',
    // Suggestion category icons
    'i-lucide-user-check',
    'i-lucide-pen-tool',
    'i-lucide-shield-alert',
    'i-lucide-user-x',
    'i-lucide-paintbrush',
    'i-lucide-git-branch',
    'i-lucide-clipboard-list',
    'i-lucide-bot',
    'i-lucide-box',
    'i-lucide-list-ordered',
    'i-lucide-check-circle',
    // User menu & settings
    'i-lucide-user-circle',
    'i-lucide-user',
    'i-lucide-cpu',
    'i-lucide-brain',
    'i-lucide-log-out',
    'i-lucide-toggle-right',
    'i-lucide-activity',
    'i-lucide-lock',
    'i-lucide-lock-open',
    'i-lucide-settings',
    // Mode tab icons (创作页)
    'i-lucide-book-copy',
    'i-lucide-text-cursor-input',
    'i-lucide-star',
    'i-lucide-layers',
    'i-lucide-folder-plus',
  ],
})
